import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  // Global & Reusable Styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F8FF',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#6B7280',
  },
  curvedHeader: {
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    width: '100%',
  },
  headerLeft: {
    flex: 1,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    color: '#374151',
    marginBottom: 16,
  },
  faqItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },

  // Home Screen
  homeHeaderGradient: {
    paddingTop: 50,
    paddingBottom: 20,
  },
  modernDashboardHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    width: '100%',
  },
  modernDashboardProfile: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modernDashboardAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  modernDashboardProfileInfo: {},
  modernDashboardWelcome: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  modernDashboardName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  whiteHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  gradientNotificationButton: {
    marginLeft: 16,
    position: 'relative',
  },
  gradientNotificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#0277BD',
  },
  gradientNotificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  heroFeatures: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  heroFeature: {
    alignItems: 'center',
  },
  heroFeatureText: {
    fontSize: 14,
    fontWeight: '600',
  },
  heroFeatureSeparator: {
    width: 1,
    height: '60%',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignSelf: 'center',
  },
  decorativeShape1: {
    position: 'absolute',
    top: -50,
    left: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(2, 119, 189, 0.1)',
  },
  decorativeShape2: {
    position: 'absolute',
    bottom: -80,
    right: -80,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
  },
  homeSearchSection: {
    paddingHorizontal: 20,
    marginTop: -20,
    marginBottom: 10,
    zIndex: 10,
  },
  promotionalBannersSection: {
    marginTop: 10,
    marginBottom: 20,
  },
  featuredEventsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  featuredEventsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  featuredEventsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
  },
  seeAllLink: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0277BD',
  },
  premiumFeaturedContainer: {
    gap: 16,
  },
  horizontalEventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  premiumFeaturedBadge: {
    position: 'absolute',
    top: 12,
    left: -1,
    zIndex: 1,
  },
  premiumBadgeGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  premiumBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  horizontalEventImageContainer: {
    width: 120,
    height: '100%',
  },
  horizontalEventImage: {
    width: '100%',
    height: '100%',
  },
  horizontalEventImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalEventHeartButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalEventDetailsContainer: {
    flex: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  horizontalEventTopSection: {},
  horizontalEventTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  horizontalEventMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  horizontalEventMetaText: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 6,
  },
  horizontalEventBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  horizontalEventPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#059669',
  },
  horizontalEventViewButton: {
    backgroundColor: '#E0F2FE',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  horizontalEventViewButtonText: {
    color: '#0277BD',
    fontWeight: '600',
    fontSize: 12,
  },
  creativeElementsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  statsCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 20,
  },
  statsCard: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  statsCardGradient: {
    padding: 16,
    alignItems: 'center',
  },
  statsCardNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 8,
  },
  statsCardLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  organizerBox: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  organizerBoxGradient: {
    padding: 20,
  },
  organizerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  organizerTextSection: {
    flex: 1,
  },
  organizerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  organizerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 4,
  },
  organizerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginLeft: 16,
  },
  organizerButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: 8,
  },

  // AutoScrollingPromoCarousel
  promotionalBannersContainer: {
    marginBottom: 10,
  },
  heroBanner: {
    borderRadius: 20,
    padding: 16,
    height: 120,
    justifyContent: 'center',
  },
  heroBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroBannerTextSectionWithImage: {
    flex: 1,
  },
  heroBannerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  heroBannerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 12,
    lineHeight: 18,
  },
  heroBannerButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  heroBannerButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 12,
  },
  heroBannerImageSection: {
    marginLeft: 10,
  },
  heroBannerPromoImagePrimary: { width: 100, height: 100 },
  heroBannerPromoImageSecondary: { width: 100, height: 100 },
  heroBannerPromoImageTertiary: { width: 100, height: 100 },
  heroBannerPromoImageQuaternary: { width: 100, height: 100 },
  heroBannerPromoImageQuinary: { width: 100, height: 100 },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D1D5DB',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: '#0277BD',
    width: 12,
  },
  notificationsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  notificationsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  notificationsCloseButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.05)',
  },
  notificationsEmpty: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  notificationsEmptyText: {
    color: '#6B7280',
    marginTop: 8,
  },
  notificationsList: {
    maxHeight: 320,
    paddingVertical: 4,
  },
  notificationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  notificationItemDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#0284C7',
    marginRight: 10,
  },
  notificationItemText: {
    flex: 1,
  },
  notificationItemTitle: {
    color: '#0F172A',
    fontWeight: '600',
    fontSize: 14,
  },
  notificationItemTime: {
    color: '#6B7280',
    fontSize: 12,
    marginTop: 2,
  },
  notificationsActions: {
    marginTop: 8,
    alignItems: 'flex-end',
  },
  notificationsClearButton: {
    backgroundColor: '#E0F2FE',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  notificationsClearButtonText: {
    color: '#0369A1',
    fontWeight: '700',
    fontSize: 12,
  },
  // Notifications overlay/panel
  notificationsOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    paddingTop: 80,
    paddingHorizontal: 16,
    alignItems: 'flex-end',
  },
  notificationsPanel: {
    width: '92%',
    maxWidth: 420,
    maxHeight: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
  },
  notificationsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  notificationsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  notificationsCloseButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.05)'
  },
  notificationsEmpty: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  notificationsEmptyText: {
    color: '#6B7280',
    marginTop: 8,
  },
  notificationsList: {
    maxHeight: 320,
    paddingVertical: 4,
  },
  notificationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  notificationItemDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#0284C7',
    marginRight: 10,
  },
  notificationItemText: {
    flex: 1,
  },
  notificationItemTitle: {
    color: '#0F172A',
    fontWeight: '600',
    fontSize: 14,
  },
  notificationItemTime: {
    color: '#6B7280',
    fontSize: 12,
    marginTop: 2,
  },
  notificationsActions: {
    marginTop: 8,
    alignItems: 'flex-end',
  },
  notificationsClearButton: {
    backgroundColor: '#E0F2FE',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  notificationsClearButtonText: {
    color: '#0369A1',
    fontWeight: '700',
    fontSize: 12,
  },

  // Profile Screen
  profileHeader: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 20,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    marginBottom: 12,
  },
  profileName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  profileEmail: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  profileContent: {
    padding: 20,
  },
  profileMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  profileMenuItemIcon: {
    marginRight: 16,
  },
  profileMenuItemText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  logoutButton: {
    marginTop: 20,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
    borderWidth: 1,
  },

  // Modern Organizer Login
  modernOrganizerContainer: {
    flex: 1,
    backgroundColor: '#F4F8FF',
  },
  modernOrganizerHeader: {
    paddingTop: 60,
    paddingBottom: 40,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  modernOrganizerHeaderIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  modernOrganizerHeaderTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  modernOrganizerHeaderSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    marginTop: 4,
  },
  modernOrganizerFormCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 24,
    marginTop: -20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 15,
  },
  modernOrganizerFormTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 24,
  },
  modernOrganizerError: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  modernOrganizerErrorText: {
    marginLeft: 8,
    color: '#EF4444',
    fontWeight: '500',
  },
  modernOrganizerSuccess: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  modernOrganizerSuccessText: {
    marginLeft: 8,
    color: '#10B981',
    fontWeight: '500',
  },
  modernOrganizerInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 12,
  },
  modernOrganizerInputIconContainer: {
    paddingRight: 8,
  },
  modernOrganizerInput: {
    flex: 1,
    height: 52,
    fontSize: 16,
    color: '#1F2937',
  },
  modernOrganizerInputFocused: {
    backgroundColor: '#FFFFFF',
    borderColor: '#0277BD',
    borderWidth: 1,
  },
  modernOrganizerEyeIcon: {
    padding: 8,
  },
  modernOrganizerForgotButton: {
    alignSelf: 'flex-end',
    marginBottom: 16,
  },
  modernOrganizerForgotText: {
    color: '#0277BD',
    fontWeight: '600',
  },
  modernOrganizerPrimaryButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  modernOrganizerPrimaryButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  modernOrganizerPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  modernOrganizerDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  modernOrganizerDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  modernOrganizerDividerText: {
    marginHorizontal: 12,
    color: '#9CA3AF',
    fontWeight: '500',
  },
  modernOrganizerSocialButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
  },
  modernOrganizerSocialButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernOrganizerToggleButton: {
    marginTop: 24,
    alignItems: 'center',
  },
  modernOrganizerToggleText: {
    color: '#6B7280',
  },
  modernOrganizerToggleTextBold: {
    fontWeight: '700',
    color: '#0277BD',
  },
  modernOrganizerFeaturesSection: {
    padding: 20,
  },
  modernOrganizerFeaturesTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 16,
    textAlign: 'center',
  },
  modernOrganizerFeatureCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
  },
  modernOrganizerFeatureIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(2, 119, 189, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  modernOrganizerFeatureContent: {
    flex: 1,
  },
  modernOrganizerFeatureTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  modernOrganizerFeatureDescription: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 2,
  },
  forgotPasswordOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  forgotPasswordModal: {
    width: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
  },
  forgotPasswordHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  forgotPasswordTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2937',
  },
  forgotPasswordSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
  },
  forgotPasswordForm: {},
  simpleInputGroup: {
    marginBottom: 16,
  },
  simpleInputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  simpleInput: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#1F2937',
  },
  simpleButton: {
    backgroundColor: '#0277BD',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  simpleButtonDisabled: {
    backgroundColor: '#A0AEC0',
  },
  simpleButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  simpleToggle: {
    marginTop: 16,
    alignItems: 'center',
  },
  simpleToggleText: {
    color: '#6B7280',
    fontWeight: '600',
  },
});
