import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const homeStyles = StyleSheet.create({
  // Decorative background shapes for Home
  creativeBlobBlue: {
    position: 'absolute',
    top: 150,
    right: -120,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(179, 199, 184, 0.46)',
    zIndex: 0,
  },
  creativeBlobGreen: {
    position: 'absolute',
    top: 2300,
    left: 350,
    width: 100,
    height: 100,
    borderRadius: 90,
    backgroundColor: 'rgba(197, 177, 177, 0.9)',
    zIndex: 0,
  },
  creativeBlobYellow: {
    position: 'absolute',
    top: 1080,
    right: 120,
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: 'rgba(250, 58, 0, 0.38)',
    zIndex: 0,
  },
  // Decorative background orbs
  pageBackground: {
    position: 'absolute',
    top: -340,
    left: -120,
    right: -120,
    height: 520,
    zIndex: -1,
  },
  backgroundOrbOne: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(207, 203, 191, 0.88)',
    top: -50,
    left: -100,
  },
  backgroundOrbTwo: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 180,
    backgroundColor: 'rgba(204, 170, 116, 0.5)',
    top: 250,
    right: -40,
  },
  backgroundOrbThree: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 130,
    backgroundColor: 'rgba(226, 103, 2, 0.9)',
    top: 780,
    left: 0,
  },
  backgroundOrbFour: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(245, 99, 2, 0.93)',
    top: 50,
    right: -50,
  },
  backgroundOrbFive: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(247, 92, 2, 0.97)8)',
    top: 920,
    left: 0,
  },
  backgroundOrbSix: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(240, 238, 238, 0.94)',
    top: 800,
    left: -10,
  },
  backgroundOrbSeven: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(245, 60, 14, 0.98)',
    top: 700,
    left: 40,
  },
  backgroundOrbEight: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 10,
    backgroundColor: 'rgba(165, 161, 159, 0.47)',
    top: 250,
    left: -80,
  },
  backgroundOrbNine: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 35,
    backgroundColor: 'rgba(177, 177, 176, 0.75)',
    top: 700,
    right: 120,
  },
  backgroundOrbTen: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(55, 0, 255, 0.9)',
    top: 600,
    right: 100,
  },
  backgroundOrbEleven: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 70,
    backgroundColor: 'rgba(195, 197, 196, 0.92)',
    top: 1350,
    left: -20,
  },
  backgroundOrbTwelve: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(199, 195, 192, 0.94)',
    top: 1500,
    right: -60,
  },
  backgroundOrbThirteen: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(236, 6, 6, 0.97)',
    top: 650,
    left: 80,
  },
  backgroundOrbFourteen: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(250, 10, 2, 0.97)',
    top: 580,
    right: 150,
  },
  backgroundOrbFifteen: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 41, 3, 1)',
    top: 650,
    left: -20,
  },
  // Countdown card styles
  countdownCard: {
    marginBottom: 16,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#0277BD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  countdownInlineContainer: {
    marginTop: -12,
    marginBottom: 8,
    marginHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#060B14',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
    shadowColor: 'rgba(0, 0, 0, 1)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'visible',
  },
  countdownInlineDepthLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    overflow: 'hidden',
    zIndex: 1,
  },
  countdownInlineGlowOrbOne: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    top: -60,
    left: -60,
    backgroundColor: 'rgba(2, 119, 189, 0.35)',
    zIndex: 2,
  },
  countdownInlineGlowOrbTwo: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    bottom: -80,
    right: -80,
    backgroundColor: 'rgba(1, 87, 155, 0.30)',
    zIndex: -1,
  },
  countdownInlineHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '55%',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    transform: [{ skewY: '-8deg' }],
    opacity: 0.5,
    zIndex: -1,
  },
  countdownInlineHighlightBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '55%',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    transform: [{ skewY: '8deg' }],
    opacity: 0.5,
    zIndex: -1,
  },
  countdownInlineContent: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 4,
    zIndex: 2,
    elevation: 2,
  },
  countdownInlineCarouselViewport: {
    overflow: 'hidden',
    borderRadius: 20,
    zIndex: 3,
  },
  countdownInlineCarouselTrack: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  countdownInlineCarouselSlide: {
    position: 'relative',
  },
  countdownInlineLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  countdownInlineIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(0, 0, 0, 1)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 6,
  },
  countdownInlineTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  countdownInlineTimerPill: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    shadowColor: 'rgba(0, 0, 0, 1)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 14,
    elevation: 7,
  },
  countdownGradient: {
    padding: 16,
  },
  countdownContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  countdownLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  countdownIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  countdownTextContainer: {
    flex: 1,
  },
  countdownLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.78)',
    marginBottom: 2,
  },
  countdownEventTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  countdownEventImageWrapper: {
    width: 60,
    height: 60,
    borderRadius: 30,
    overflow: 'hidden',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countdownEventImage: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
  },
  countdownRight: {
    marginLeft: 12,
  },
  countdownTimer: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  // Skeleton loading styles
  skeleton: {
    backgroundColor: '#E0E7FF',
    borderRadius: 4,
    opacity: 0.7,
  },
  // Background Decoratives
  backgroundDecorative: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    zIndex: -1,
  },
  backgroundOrbOne: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    top: -200,
    right: 150,
    backgroundColor: 'rgba(156, 155, 155, 0.42))',
    zIndex: -1,
  },
  backgroundOrbTwo: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    bottom: 200,
    left: -50,
    backgroundColor: 'rgba(139, 92, 246, 0.22)',
    zIndex: -1,
  },
  backgroundOrbThree: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    top: '40%',
    left: '60%',
    backgroundColor: 'rgba(16, 185, 129, 0.20)',
    zIndex: -1,
  },
  backgroundPatternOne: {
    position: 'absolute',
    width: 100,
    height: 100,
    top: '20%',
    left: '10%',
    transform: [{ rotate: '45deg' }],
    backgroundColor: 'rgba(255, 3, 3, 0.75)',
    zIndex: -1,
  },
  backgroundPatternTwo: {
    position: 'absolute',
    width: 80,
    height: 80,
    bottom: '30%',
    right: '15%',
    transform: [{ rotate: '30deg' }],
    backgroundColor: 'rgba(245, 158, 11, 0.17)',
    zIndex: -1,
  },
  // Creative Shapes
  waveOne: {
    position: 'absolute',
    width: 300,
    height: 300,
    top: 80,
    left: -50,
    backgroundColor: 'rgba(1, 54, 97, 0.44)',
    borderRadius: 100,
    transform: [{ scaleX: 2 }, { scaleY: 0.5 }],
    zIndex: -1,
  },
  waveTwo: {
    position: 'absolute',
    width: 180,
    height: 90,
    top: '60%',
    right: -40,
    backgroundColor: 'rgba(168, 85, 247, 0.15)',
    borderRadius: 90,
    transform: [{ scaleX: 2.5 }, { scaleY: 0.4 }, { rotate: '15deg' }],
    zIndex: -1,
  },
  circleOne: {
    position: 'absolute',
    width: 60,
    height: 60,
    top: '25%',
    right: '20%',
    backgroundColor: 'rgba(34, 197, 94, 0.14)',
    borderRadius: 30,
    zIndex: -1,
  },
  circleTwo: {
    position: 'absolute',
    width: 40,
    height: 40,
    bottom: '20%',
    left: '25%',
    backgroundColor: 'rgba(251, 146, 60, 0.16)',
    borderRadius: 20,
    zIndex: -1,
  },
  triangleOne: {
    position: 'absolute',
    width: 0,
    height: 0,
    top: '45%',
    left: '15%',
    borderLeftWidth: 40,
    borderLeftColor: 'transparent',
    borderRightWidth: 40,
    borderRightColor: 'transparent',
    borderBottomWidth: 70,
    borderBottomColor: 'rgba(236, 72, 153, 0.15)',
    transform: [{ rotate: '180deg' }],
    zIndex: -1,
  },
  hexagonOne: {
    position: 'absolute',
    width: 80,
    height: 80,
    bottom: '15%',
    right: '30%',
    backgroundColor: 'rgba(14, 165, 233, 0.14)',
    borderRadius: 18,
    transform: [{ rotate: '20deg' }],
    zIndex: -1,
  },
  backgroundOrbFour: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    top: '75%',
    left: '-20%',
    backgroundColor: 'rgba(2, 119, 189, 0.14)',
    zIndex: -1,
  },
  backgroundOrbFive: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    top: '18%',
    right: '-15%',
    backgroundColor: 'rgba(245, 158, 11, 0.14)',
    zIndex: -1,
  },
  backgroundRingOne: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    top: '35%',
    left: '-25%',
    borderWidth: 2,
    borderColor: 'rgba(99, 102, 241, 0.18)',
    backgroundColor: 'transparent',
    zIndex: -1,
  },
  backgroundRingTwo: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    bottom: '12%',
    right: '-18%',
    borderWidth: 2,
    borderColor: 'rgba(16, 185, 129, 0.18)',
    backgroundColor: 'transparent',
    zIndex: -1,
  },
  backgroundDotOne: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    top: '28%',
    left: '72%',
    backgroundColor: 'rgba(2, 119, 189, 0.25)',
    zIndex: -1,
  },
  backgroundDotTwo: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    top: '55%',
    left: '12%',
    backgroundColor: 'rgba(168, 85, 247, 0.25)',
    zIndex: -1,
  },
  backgroundDotThree: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    bottom: '22%',
    left: '52%',
    backgroundColor: 'rgba(245, 158, 11, 0.28)',
    zIndex: -1,
  },
  backgroundStripeOne: {
    position: 'absolute',
    width: 140,
    height: 16,
    borderRadius: 10,
    top: '48%',
    right: '-10%',
    backgroundColor: 'rgba(236, 72, 153, 0.14)',
    transform: [{ rotate: '-18deg' }],
    zIndex: -1,
  },
  backgroundStripeTwo: {
    position: 'absolute',
    width: 160,
    height: 18,
    borderRadius: 12,
    bottom: '34%',
    left: '-12%',
    backgroundColor: 'rgba(59, 130, 246, 0.14)',
    transform: [{ rotate: '16deg' }],
    zIndex: -1,
  },
  // Additional decorative elements
  decorativeBlobOne: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    top: '15%',
    left: '5%',
    backgroundColor: 'rgba(236, 72, 153, 0.12)',
    transform: [{ rotate: '45deg' }],
    zIndex: -1,
  },
  decorativeBlobTwo: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    top: '55%',
    right: '8%',
    backgroundColor: 'rgba(245, 158, 11, 0.13)',
    transform: [{ rotate: '-30deg' }],
    zIndex: -1,
  },
  decorativeBlobThree: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    bottom: '25%',
    left: '15%',
    backgroundColor: 'rgba(34, 197, 94, 0.14)',
    transform: [{ rotate: '60deg' }],
    zIndex: -1,
  },
  decorativeOrbSix: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    top: '30%',
    right: '-10%',
    backgroundColor: 'rgba(139, 92, 246, 0.14)',
    zIndex: -1,
  },
  decorativeOrbSeven: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    bottom: '40%',
    left: '-8%',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    zIndex: -1,
  },
  decorativeCircleThree: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    top: '35%',
    left: '35%',
    backgroundColor: 'rgba(251, 146, 60, 0.16)',
    zIndex: -1,
  },
  decorativeCircleFour: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    bottom: '18%',
    right: '25%',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    zIndex: -1,
  },
  decorativeWaveThree: {
    position: 'absolute',
    width: 250,
    height: 120,
    top: '45%',
    left: '-15%',
    backgroundColor: 'rgba(99, 102, 241, 0.13)',
    borderRadius: 120,
    transform: [{ scaleX: 2.2 }, { scaleY: 0.6 }, { rotate: '-25deg' }],
    zIndex: -1,
  },
  decorativeWaveFour: {
    position: 'absolute',
    width: 220,
    height: 100,
    bottom: '15%',
    right: '-20%',
    backgroundColor: 'rgba(236, 72, 153, 0.12)',
    borderRadius: 110,
    transform: [{ scaleX: 2.8 }, { scaleY: 0.5 }, { rotate: '35deg' }],
    zIndex: -1,
  },
  decorativeCrossOne: {
    position: 'absolute',
    width: 60,
    height: 60,
    top: '22%',
    right: '18%',
    backgroundColor: 'rgba(2, 119, 189, 0.15)',
    transform: [{ rotate: '45deg' }],
    zIndex: -1,
  },
  decorativeCrossTwo: {
    position: 'absolute',
    width: 50,
    height: 50,
    bottom: '32%',
    left: '28%',
    backgroundColor: 'rgba(168, 85, 247, 0.14)',
    transform: [{ rotate: '30deg' }],
    zIndex: -1,
  },
  decorativeDotFour: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    top: '42%',
    right: '38%',
    backgroundColor: 'rgba(245, 158, 11, 0.25)',
    zIndex: -1,
  },
  decorativeDotFive: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    bottom: '28%',
    left: '42%',
    backgroundColor: 'rgba(34, 197, 94, 0.24)',
    zIndex: -1,
  },
  decorativeDotSix: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    top: '65%',
    right: '15%',
    backgroundColor: 'rgba(236, 72, 153, 0.22)',
    zIndex: -1,
  },
  // Home Screen
  curvedHeader: {
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 7,
  },
  modernHeaderContainer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modernHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modernHeaderTextGroup: {
    flexDirection: 'column',
    gap: 2,
  },
  modernHeaderTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
  },
  modernHeaderSubtitle: {
    fontSize: 13,
    color: '#64748B',
  },
  modernHeaderSearchButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeHeaderContainer: {
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 1,
  },
  homeHeaderCard: {
    borderRadius: 30,
    padding: 20,
    shadowColor: 'rgba(0, 0, 0, 1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    position: 'relative',
    overflow: 'hidden',
    gap: 14,
  },
  homeHeaderBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  homeHeaderOrbOne: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    top: -120,
    left: -90,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  homeHeaderOrbTwo: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    bottom: -150,
    right: -120,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
  },
  homeHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  homeHeaderWelcomeText: {
    left:0,
    fontSize: 17,
    color: 'rgba(255, 255, 255, 1)',
  },
  homeHeaderNameText: {
    fontSize: 20,
    left:0,
    fontWeight: '800',
    color: 'rgba(255, 255, 255, 1)',
    marginTop: 2,
  },
  homeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  homeHeaderIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(15, 23, 42, 0.08)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    position: 'relative',
  },
  homeHeaderIconBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: 'rgba(239, 68, 68, 1)',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeHeaderIconBadgeText: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 10,
    fontWeight: '700',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#0277BD',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
  },
  homeHeaderMetaRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  homeHeaderMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  homeHeaderMetaText: {
    fontSize: 12,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: -3,
    color: 'rgba(255, 255, 255, 1)',
  },
  homeHeaderMetaSeparator: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 8,
  },
  homeHeaderTitle: {
    color: 'rgba(15, 23, 42, 1)',
  },
  homeHeaderSubtitle: {
    color: 'rgba(71, 85, 105, 1)',
  },
  homeHeaderBackground: {
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(15, 23, 42, 0.05)',
  },
  homeHeaderGradient: {
    paddingTop: 10,
    paddingBottom: 20,
  },
  modernDashboardHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  modernDashboardHeaderTopAdjusted: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  modernDashboardProfile: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modernDashboardAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  modernDashboardAvatarInner: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  eventopiaLogo: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  modernDashboardAvatarImage: {
    width: 50,
    height: 50,
    borderRadius: 23,
  },
  modernDashboardProfileInfo: {},
  modernDashboardWelcome: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.78)',
    marginBottom: 2,
  },
  modernDashboardNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modernDashboardName: {
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  modernDashboardEmail: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.72)',
    marginTop: 3,
  },
  modernDashboardVerifiedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  modernDashboardVerifiedText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0F172A',
  },
  modernDashboardWelcomeDark: {
    fontSize: 14,
    color: 'rgba(71, 85, 105, 1)',
  },
  modernDashboardNameDark: {
    fontSize: 30,
    fontWeight: '700',
    color: 'rgba(15, 23, 42, 1)',
  },
  whiteHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  whiteHeaderActionsAdjusted: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  gradientNotificationButton: {
    marginLeft: 0,
    position: 'relative',
  },
  gradientNotificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: 'rgba(239, 68, 68, 1)',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(2, 119, 189, 1)',
  },
  gradientNotificationBadgeText: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 10,
    fontWeight: 'bold',
  },
  heroFeatures: {
    display: 'none',
  },
  heroFeature: {
    display: 'none',
  },
  heroFeatureText: {
    display: 'none',
  },
  heroFeatureSeparator: {
    display: 'none',
  },
  decorativeShape1: {
    position: 'absolute',
    top: -50,
    left: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(0, 129, 168, 0.37)',
    opacity: 1
  },
  decorativeShape2: {
    position: 'absolute',
    bottom: -80,
    right: -80,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(5, 122, 231, 0.38)',
    opacity: 1
  },
  decorativeShape3: {
    position: 'absolute',
    top: 200,
    left: 80,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(6, 122, 74, 0.86)',
    opacity: 0.8,
  
  },
  decorativeShape4: {
    position: 'absolute',
    bottom: 200,
    right: 50,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 154, 4, 0.39)',
    opacity: 0.8,
    
  },
   decorativeShape5: {
    position: 'absolute',
    bottom: 300,
    right: 290,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(250, 79, 0, 0.39)',
    opacity: 0.8,
    
  },
  decorativeShape6: {
    position: 'absolute',
    top: '15%',
    left: '5%',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(139, 92, 246, 0.15)', 
  },
  decorativeShape7: {
    position: 'absolute',
    bottom: '10%',
    right: '5%',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
  },
  decorativeShape8: {
    position: 'absolute',
    top: '50%',
    left: '40%',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  decorativeShape9: {
    position: 'absolute',
    top: '5%',
    right: '10%',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
  },
  decorativeShape10: {
    position: 'absolute',
    bottom: '20%',
    left: '15%',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(5, 150, 105, 0.1)',
  },

  // New Advanced Decorative Elements
  largeCurvedWave: {
    position: 'absolute',
    top: 0,
    left: -100,
    right: -100,
    height: 300,
    backgroundColor: 'rgba(2, 119, 189, 0.08)',
    borderBottomLeftRadius: 1000,
    borderBottomRightRadius: 1000,
    transform: [{ scaleX: 2 }],
  },

  vibrantAccentRing1: {
    position: 'absolute',
    bottom: '25%',
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },

  vibrantAccentRing2: {
    position: 'absolute',
    bottom: '22%',
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 2,
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },

  headerAura: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    width: width * 1.2,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(2, 119, 189, 0.15)',
    // A blur effect would be ideal here if available, this simulates it
    transform: [{ scale: 1.5 }],
  },
  homeSearchSection: {
    paddingHorizontal: 20,
    marginTop: 16,
    marginBottom: 12,
  },
  promotionalBannersSection: {
    marginTop: 10,
    marginBottom: 20,
    
  },
  categoriesContainer: {
    backgroundColor: 'transparent',
    marginBottom: 8,
    marginTop: -12,
    maxHeight: 50,
  },
  categoriesContent: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 6,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#060B14',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
    marginRight: 6,
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
    gap: 3,
    maxWidth: 120,
    overflow: 'hidden',
  },
  categoryDepthLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  categoryGlowOrbOne: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    top: -60,
    left: -50,
    backgroundColor: 'rgba(2, 119, 189, 0.35)',
  },
  categoryGlowOrbTwo: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    bottom: -80,
    right: -80,
    backgroundColor: 'rgba(1, 87, 155, 0.30)',
  },
  categoryHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '55%',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    transform: [{ skewY: '-8deg' }],
    opacity: 0.5,
  },
  categoryChipText: {
    fontSize: 11,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.8)',
    zIndex: 1,
  },
  featuredEventsSection: {
    paddingHorizontal: 8,
    marginBottom: 20,
  },
  recommendedEventsSection: {
    paddingHorizontal: 10,
    marginBottom: 24,
  },
  featuredEventsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 0,
    marginBottom: 16,
  },
  featuredEventsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: 'rgb(1, 33, 78)',
  },
  seeAllLink: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(2, 119, 189, 1)',
  },
  premiumFeaturedContainer: {
    gap: 16,
  },
  recommendedEventsList: {
    gap: 16,
  },
  recommendedEventsScrollContainer: {
    gap: 16,
  },
  recommendedEventCard: {
    width: width * 0.82,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: 'rgba(0, 51, 80, 0.99)',
    shadowColor: 'rgba(0, 0, 0, 0.96)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 25,
    elevation: 8,
  },
  recommendedEventImage: {
    width: '100%',
    height: 200,
  },
  recommendedEventOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  recommendedEventOverlayContent: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: 20,
  },
  recommendedEventTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  recommendedEventMetaRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  recommendedEventMetaText: {
    marginLeft: 6,
    color: 'rgba(255,255,255,0.95)',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  popularOrganizersSection: {
    paddingHorizontal: 10,
    marginBottom: 24,
  },
  popularOrganizersScrollContainer: {
    paddingRight: 10,
    gap: 12,
  },
  popularOrganizerCard: {
    width: 140,
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(1, 33, 78, 0.10)',
  },
  popularOrganizerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  popularOrganizerName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  popularOrganizerRatingRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  popularOrganizerRatingText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
  },
  popularOrganizerMeta: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  horizontalEventCard: {
    height: 130,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 10,
    width: '100%',
    alignSelf: 'stretch',
    marginBottom: 18,
    marginHorizontal: 0,
    overflow: 'hidden',
    elevation: 5,           // less shadow
    shadowColor: '#00',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  premiumFeaturedBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 10,
  },
  premiumFeaturedBadgeLeft: {
    position: 'absolute',
    top: 8,
    left: 8,
    zIndex: 10,
  },
  premiumBadgeGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  premiumBadgeText: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  horizontalEventImageContainer: {
    width: 120,
    height: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
    top:0,
    left:10,
    borderRightWidth: 11,
    borderRightColor: 'rgba(255, 255, 255, 0.15)',
  },
  horizontalEventImage: {
    right:20,
    width: 130,
    height: 130,
    borderRadius: 3,
  },
  horizontalEventImagePlaceholder: {
    width: 120,
    height: 140,
    backgroundColor: '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalEventHeartButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalEventDetailsContainer: {
    flex: 1,
    padding: 12,
    justifyContent: 'center',
  },
  horizontalEventTopSection: {},
  horizontalEventTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: 'rgba(31, 41, 55, 1)',
    marginBottom: 4,
  },
  horizontalEventStatusContainer: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  horizontalEventTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.1)',
  },
  horizontalEventTagFeatured: {
    backgroundColor: 'rgba(234, 179, 8, 0.2)',
  },
  horizontalEventTagUpcoming: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
  },
  horizontalEventTagText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1e293b',
    marginBottom: 2,
  },
  horizontalEventMetaRow: {
    flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 2,
  },
  horizontalEventMetaText: {
    fontSize: 12,
  color: '#64748b',
  marginLeft: 6,
  },
  horizontalEventBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  horizontalEventPrice: {
  fontSize: 13,
  fontWeight: '600',
  color: '#0277BD',
},
  horizontalEventViewButton: {
    backgroundColor: 'rgba(2, 119, 189, 1)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  horizontalEventViewButtonText: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '600',
    fontSize: 12,
  },
  creativeElementsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  statsCardsContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
    width: '100%',
    marginBottom: 20,
  },
  statsCard: {
    flexGrow: 1,
    flexBasis: 0,
    height: 120,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: 'rgba(0, 0, 0, 1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    position: 'relative',
  },
  statsCardGradient: {
    flex: 1,
    padding: 16,
    alignItems: 'center',
    borderRadius: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  statsCardDepthLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  statsCardGlowOrbOne: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    top: -20,
    right: -20,
    blurRadius: 20,
  },
  statsCardGlowOrbTwo: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
    bottom: -15,
    left: -15,
    blurRadius: 15,
  },
  statsCardHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    pointerEvents: 'none',
  },
  statsCardNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 1)',
    marginTop: 8,
  },
  statsCardLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  organizerBox: {
    bottom: 18,
    marginHorizontal: 10,
    borderRadius: 30,
    overflow: 'hidden',
    shadowColor: 'rgba(0, 0, 0, 1)',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.55,
    shadowRadius: 22,
    elevation: 10,
  },
  organizerBoxGradient: {
    padding: 20,
    backgroundColor: '#060B14',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
    borderRadius: 30,
  },
  organizerBoxDepthLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  organizerBoxGlowOrbOne: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    top: -120,
    left: -110,
    backgroundColor: 'rgba(2, 119, 189, 0.35)',
  },
  organizerBoxGlowOrbTwo: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    bottom: -140,
    right: -140,
    backgroundColor: 'rgba(1, 87, 155, 0.30)',
  },
  organizerBoxHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '55%',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    transform: [{ skewY: '-8deg' }],
    opacity: 0.5,
  },
  organizerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  organizerTextSection: {
    flex: 1,
  },
  organizerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 1)',
  },
  organizerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 4,
  },
  organizerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginLeft: 16,
  },
  organizerButtonText: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '600',
    marginLeft: 8,
  },

  // Notifications modal

  // AutoScrollingPromoCarousel
  promotionalBannersContainer: {
    marginBottom: 10,
  },
  heroBanner: {
    borderRadius: 20,
    padding: 16,
    height: 200,
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(251, 251, 252, 0.94)',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  heroBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroBannerTextSectionWithImage: {
    flex: 1,
  },
  heroBannerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 1)',
    marginBottom: 4,
  },
  heroBannerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 12,
    lineHeight: 18,
  },
  heroBannerButton: {
    backgroundColor: 'rgba(255, 255, 255, 1)',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  heroBannerButtonText: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '600',
    fontSize: 10,
  },
  heroBannerImageSection: {
    marginLeft: 10,
  },
  heroBannerPromoImagePrimary: { width: 200, height: 200 },
  heroBannerPromoImageSecondary: { width: 100, height: 100 },
  heroBannerPromoImageTertiary: { width: 100, height: 100 },
  heroBannerPromoImageQuaternary: { width: 100, height: 100 },
  heroBannerPromoImageQuinary: { width: 100, height: 100 },
  // Individual controllers for each banner image
  heroBannerImage1: {
    width: 350,
    height: 200,
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 0,
    marginTop: 50,
    marginBottom: 0,
  },
  heroBannerImage2: {
    width: 350,
    height: 200,
    borderRadius: 20,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 50,
    marginBottom: 0,
  },
  heroBannerImage3: {
    width: 350,
    height: 200,
    borderRadius: 20,
    marginLeft: 0,
    marginRight: 25,
    marginTop: 50,
    marginBottom: 0,
  },
  heroBannerImage4: {
    width: 550,
    height: 220,
    borderRadius: 20,
    marginLeft: 50,
    marginRight: 40,
    marginTop: 28,
    marginBottom: 0,
  },
  heroBannerImage5: {
    width: 450,
    height: 180,
    borderRadius: 20,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 50,
    marginBottom: 0,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(209, 213, 219, 1)',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: 'rgba(2, 119, 189, 1)',
    width: 12,
  },

  // Trending Events Section
  trendingEventsSection: {
    marginTop: 18,
    marginBottom: 24,
  },
  trendingEventsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  trendingTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trendingEventsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  trendingEventsContainer: {
    marginBottom: 16,
  },
  trendingEventsScrollContainer: {
    paddingHorizontal: 10,
    gap: 12,
  },
  trendingEventCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 16,
    shadowColor: 'rgba(0, 0, 0, 0.3)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
    overflow: 'hidden',
    height: 310,
    width: 240,
    marginVertical: 4,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 1)',
  },
  trendingEventCardOrbOne: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(183, 233, 3, 0.4)',
    top: -20,
    right: -20,
    zIndex: 0,
  },
  trendingEventCardOrbTwo: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(1, 93, 116, 0.3)',
    bottom: -30,
    left: -30,
    zIndex: 0,
  },
  trendingEventCardOrbThree: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 55,
    backgroundColor: 'rgba(119, 82, 2, 0.35)',
    bottom: 95,
    right: -15,
    zIndex: 0,
  },
  trendingEventImageContainer: {
    width: '100%',
    height: 180,
  },
  trendingEventImage: {
    width: '100%',
    height: '100%',
  },
  trendingEventPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trendingEventContent: {
    padding: 12,
  },
  trendingEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  trendingEventTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 20,
    marginRight: 12,
  },
  trendingHeartButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trendingEventMeta: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  trendingMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trendingMetaText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
  },
  trendingEventFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trendingLocationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  trendingLocationText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
    flex: 1,
  },
  trendingPriceBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 16,
  },
  trendingPriceText: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(15, 23, 42, 0.95)',
  },
  // Skeleton Loader Styles
  skeletonContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  skeletonHeader: {
    marginBottom: 24,
  },
  skeletonTitle: {
    width: 120,
    height: 24,
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
    marginBottom: 8,
  },
  skeletonSubtitle: {
    width: 80,
    height: 16,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
  },
  skeletonEventsContainer: {
    marginBottom: 24,
  },
  skeletonEventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  skeletonImage: {
    width: '100%',
    height: 120,
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
    marginBottom: 12,
  },
  skeletonContent: {
    gap: 8,
  },
  skeletonMeta: {
    width: 100,
    height: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  skeletonButton: {
    width: 80,
    height: 32,
    backgroundColor: '#E5E7EB',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  skeletonStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  skeletonStatCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  skeletonIcon: {
    width: 32,
    height: 32,
    backgroundColor: '#E5E7EB',
    borderRadius: 16,
    marginBottom: 8,
  },
  skeletonValue: {
    width: 40,
    height: 20,
    backgroundColor: '#E5E7EB',
    borderRadius: 8,
    marginBottom: 4,
  },
  skeletonLabel: {
    width: 60,
    height: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  // Empty State Styles
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 60,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  emptyStateIllustration: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  emptyStateTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptyStateDescription: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    maxWidth: 280,
  },
  emptyStateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0277BD',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  emptyStateButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  // Promotion Section Styles
  promotionSection: {
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 20,
  },
  promotionLayout: {
    flexDirection: 'row',
    gap: 12,
  },
  promotionVerticalCard: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  promotionVerticalImageContainer: {
    position: 'relative',
    height: 250,
  },
  promotionVerticalImage: {
    width: '100%',
    height: '100%',
  },
  promotionBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(2, 119, 189, 0.92)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  promotionBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  promotionVerticalContent: {
    padding: 14,
    gap: 8,
  },
  promotionVerticalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    lineHeight: 22,
  },
  promotionVerticalMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  promotionVerticalMetaText: {
    fontSize: 12,
    color: '#6B7280',
    flex: 1,
  },
  promotionVerticalPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0277BD',
    marginTop: 4,
  },
  promotionHorizontalContainer: {
    flex: 1,
    gap: 12,
  },
  promotionHorizontalCard: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  promotionHorizontalImageContainer: {
    height: 125,
  },
  promotionHorizontalImage: {
    width: '100%',
    height: '100%',
  },
  promotionHorizontalContent: {
    padding: 12,
    gap: 6,
  },
  promotionHorizontalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2937',
    lineHeight: 20,
  },
  promotionHorizontalMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  promotionHorizontalMetaText: {
    fontSize: 11,
    color: '#6B7280',
    flex: 1,
  },
  promotionHorizontalPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0277BD',
  },
  // Promotion overlay text styles (smaller for full image cards)
  promotionOverlayTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 18,
  },
  promotionOverlayMetaText: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.92)',
  },
});

export default homeStyles;
