import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const homeStyles = StyleSheet.create({
  // Decorative background shapes for Home
  creativeBlobBlue: {
    position: 'absolute',
    top: 100,
    right: -90,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(249, 253, 5, 0.42)',
    zIndex: 0,
  },
  creativeBlobGreen: {
    position: 'absolute',
    bottom: 90,
    right: -60,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(12, 235, 160, 0.13)',
    zIndex: 0,
  },
  creativeBlobYellow: {
    position: 'absolute',
    top: 300,
    left: -40,
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(245, 158, 11, 0.11)',
    zIndex: 0,
  },
  // Home Screen
  curvedHeader: {
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 7,
  },
  homeHeaderContainer: {
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 1,
  },
  homeHeaderCard: {
    borderRadius: 30,
    padding: 20,
    shadowColor: 'rgba(147, 150, 156, 0.4)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(94, 95, 95, 0.34)',
    gap: 14,
  },
  homeHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  homeHeaderWelcomeText: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 1)',
  },
  homeHeaderNameText: {
    fontSize: 20,
    fontWeight: '800',
    color: 'rgba(255, 255, 255, 1)',
    marginTop: 2,
  },
  homeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  homeHeaderIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(15, 23, 42, 0.08)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    position: 'relative',
  },
  homeHeaderIconBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: 'rgba(239, 68, 68, 1)',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeHeaderIconBadgeText: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 10,
    fontWeight: '700',
  },
  homeHeaderMetaRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  homeHeaderMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  homeHeaderMetaText: {
    fontSize: 12,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: -3,
    color: 'rgba(255, 255, 255, 1)',
  },
  homeHeaderMetaSeparator: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 8,
  },
  homeHeaderTitle: {
    color: 'rgba(15, 23, 42, 1)',
  },
  homeHeaderSubtitle: {
    color: 'rgba(71, 85, 105, 1)',
  },
  homeHeaderBackground: {
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(15, 23, 42, 0.05)',
  },
  homeHeaderGradient: {
    paddingTop: 10,
    paddingBottom: 20,
  },
  modernDashboardHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  modernDashboardHeaderTopAdjusted: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  modernDashboardProfile: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modernDashboardAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  modernDashboardAvatarInner: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernDashboardProfileInfo: {},
  modernDashboardWelcome: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  modernDashboardWelcomeDark: {
    fontSize: 14,
    color: 'rgba(71, 85, 105, 1)',
  },
  modernDashboardName: {
    fontSize: 26,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 1)',
  },
  modernDashboardNameDark: {
    fontSize: 30,
    fontWeight: '700',
    color: 'rgba(15, 23, 42, 1)',
  },
  whiteHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  whiteHeaderActionsAdjusted: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  gradientNotificationButton: {
    marginLeft: 0,
    position: 'relative',
  },
  gradientNotificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: 'rgba(239, 68, 68, 1)',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(2, 119, 189, 1)',
  },
  gradientNotificationBadgeText: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 10,
    fontWeight: 'bold',
  },
  heroFeatures: {
    display: 'none',
  },
  heroFeature: {
    display: 'none',
  },
  heroFeatureText: {
    display: 'none',
  },
  heroFeatureSeparator: {
    display: 'none',
  },
  decorativeShape1: {
    position: 'absolute',
    top: -50,
    left: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(0, 129, 168, 0.37)',
    opacity: 1
  },
  decorativeShape2: {
    position: 'absolute',
    bottom: -80,
    right: -80,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(5, 122, 231, 0.38)',
    opacity: 1
  },
  decorativeShape3: {
    position: 'absolute',
    top: 200,
    left: 80,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(6, 122, 74, 0.86)',
    opacity: 0.8,
  
  },
  decorativeShape4: {
    position: 'absolute',
    bottom: 200,
    right: 50,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 154, 4, 0.39)',
    opacity: 0.8,
    
  },
   decorativeShape5: {
    position: 'absolute',
    bottom: 300,
    right: 290,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(250, 79, 0, 0.39)',
    opacity: 0.8,
    
  },
  decorativeShape6: {
    position: 'absolute',
    top: '15%',
    left: '5%',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(139, 92, 246, 0.15)', 
  },
  decorativeShape7: {
    position: 'absolute',
    bottom: '10%',
    right: '5%',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
  },
  decorativeShape8: {
    position: 'absolute',
    top: '50%',
    left: '40%',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  decorativeShape9: {
    position: 'absolute',
    top: '5%',
    right: '10%',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
  },
  decorativeShape10: {
    position: 'absolute',
    bottom: '20%',
    left: '15%',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(5, 150, 105, 0.1)',
  },

  // New Advanced Decorative Elements
  largeCurvedWave: {
    position: 'absolute',
    top: 0,
    left: -100,
    right: -100,
    height: 300,
    backgroundColor: 'rgba(2, 119, 189, 0.08)',
    borderBottomLeftRadius: 1000,
    borderBottomRightRadius: 1000,
    transform: [{ scaleX: 2 }],
  },

  vibrantAccentRing1: {
    position: 'absolute',
    bottom: '25%',
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },

  vibrantAccentRing2: {
    position: 'absolute',
    bottom: '22%',
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 2,
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },

  headerAura: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    width: width * 1.2,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(2, 119, 189, 0.15)',
    // A blur effect would be ideal here if available, this simulates it
    transform: [{ scale: 1.5 }],
  },
  homeSearchSection: {
    paddingHorizontal: 20,
    marginTop: 16,
    marginBottom: 12,
  },
  promotionalBannersSection: {
    marginTop: 10,
    marginBottom: 20,
  },
  featuredEventsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  featuredEventsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  featuredEventsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: 'rgb(1, 33, 78)',
  },
  seeAllLink: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(2, 119, 189, 1)',
  },
  premiumFeaturedContainer: {
    gap: 16,
  },
  horizontalEventCard: {
    height: 130,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 18,
    marginHorizontal: -10,
    overflow: 'hidden',
    elevation: 5,           // less shadow
    shadowColor: '#00',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  premiumFeaturedBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 10,
  },
  premiumBadgeGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  premiumBadgeText: {
    color: 'rgba(255, 255, 255, 1)',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  horizontalEventImageContainer: {
    width: 120,
    height: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
    top:0,
    left:10,
    borderRightWidth: 11,
    borderRightColor: 'rgba(255, 255, 255, 0.15)',
  },
  horizontalEventImage: {
    right:20,
    width: 130,
    height: 130,
    borderRadius: 3,
  },
  horizontalEventImagePlaceholder: {
    width: 120,
    height: 140,
    backgroundColor: '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalEventHeartButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalEventDetailsContainer: {
    flex: 1,
    padding: 12,
    justifyContent: 'center',
  },
  horizontalEventTopSection: {},
  horizontalEventTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: 'rgba(31, 41, 55, 1)',
    marginBottom: 4,
  },
  horizontalEventStatusContainer: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  horizontalEventTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.1)',
  },
  horizontalEventTagFeatured: {
    backgroundColor: 'rgba(234, 179, 8, 0.2)',
  },
  horizontalEventTagUpcoming: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
  },
  horizontalEventTagText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1e293b',
    marginBottom: 2,
  },
  horizontalEventMetaRow: {
    flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 2,
  },
  horizontalEventMetaText: {
    fontSize: 12,
  color: '#64748b',
  marginLeft: 6,
  },
  horizontalEventBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  horizontalEventPrice: {
  fontSize: 13,
  fontWeight: '600',
  color: '#0277BD',
},
  horizontalEventViewButton: {
    backgroundColor: 'rgba(2, 119, 189, 1)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  horizontalEventViewButtonText: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '600',
    fontSize: 12,
  },
  creativeElementsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  statsCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 20,
  },
  statsCard: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  statsCardGradient: {
    padding: 16,
    alignItems: 'center',
  },
  statsCardNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 1)',
    marginTop: 8,
  },
  statsCardLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  organizerBox: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  organizerBoxGradient: {
    padding: 20,
  },
  organizerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  organizerTextSection: {
    flex: 1,
  },
  organizerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 1)',
  },
  organizerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 4,
  },
  organizerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginLeft: 16,
  },
  organizerButtonText: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '600',
    marginLeft: 8,
  },

  // Notifications modal

  // AutoScrollingPromoCarousel
  promotionalBannersContainer: {
    marginBottom: 10,
  },
  heroBanner: {
    borderRadius: 20,
    padding: 16,
    height: 200,
    justifyContent: 'center',
  },
  heroBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroBannerTextSectionWithImage: {
    flex: 1,
  },
  heroBannerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 1)',
    marginBottom: 4,
  },
  heroBannerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 12,
    lineHeight: 18,
  },
  heroBannerButton: {
    backgroundColor: 'rgba(255, 255, 255, 1)',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  heroBannerButtonText: {
    color: 'rgba(255, 255, 255, 1)',
    fontWeight: '600',
    fontSize: 10,
  },
  heroBannerImageSection: {
    marginLeft: 10,
  },
  heroBannerPromoImagePrimary: { width: 200, height: 200 },
  heroBannerPromoImageSecondary: { width: 100, height: 100 },
  heroBannerPromoImageTertiary: { width: 100, height: 100 },
  heroBannerPromoImageQuaternary: { width: 100, height: 100 },
  heroBannerPromoImageQuinary: { width: 100, height: 100 },
  // Individual controllers for each banner image
  heroBannerImage1: {
    width: 350,
    height: 200,
    borderRadius: 10,
    marginLeft: 10,
    marginRight: -30,
    marginTop: 50,
    marginBottom: 0,
  },
  heroBannerImage2: {
    width: 350,
    height: 200,
    borderRadius: 20,
    marginLeft: 0,
    marginRight: -10,
    marginTop: 50,
    marginBottom: 0,
  },
  heroBannerImage3: {
    width: 350,
    height: 200,
    borderRadius: 20,
    marginLeft: 0,
    marginRight: 25,
    marginTop: 50,
    marginBottom: 0,
  },
  heroBannerImage4: {
    width: 550,
    height: 220,
    borderRadius: 20,
    marginLeft: 50,
    marginRight: 40,
    marginTop: 28,
    marginBottom: 0,
  },
  heroBannerImage5: {
    width: 450,
    height: 180,
    borderRadius: 20,
    marginLeft: 0,
    marginRight: -20,
    marginTop: 50,
    marginBottom: 0,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(209, 213, 219, 1)',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: 'rgba(2, 119, 189, 1)',
    width: 12,
  },

  // Trending Events Section
  trendingEventsSection: {
    marginBottom: 24,
  },
  trendingEventsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  trendingTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trendingEventsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  trendingEventsContainer: {
    marginBottom: 16,
  },
  trendingEventsScrollContainer: {
    paddingHorizontal: 10,
    gap: 12,
  },
  trendingEventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    overflow: 'hidden',
    width: 280,
    marginVertical: 4,
  },
  trendingEventImageContainer: {
    width: '100%',
    height: 100,
  },
  trendingEventImage: {
    width: '100%',
    height: '100%',
  },
  trendingEventPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trendingEventContent: {
    padding: 12,
  },
  trendingEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  trendingEventTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    lineHeight: 20,
    marginRight: 12,
  },
  trendingHeartButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trendingEventMeta: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  trendingMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trendingMetaText: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  trendingEventFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trendingLocationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  trendingLocationText: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
    flex: 1,
  },
  trendingPriceBadge: {
    backgroundColor: '#F0F9FF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 16,
  },
  trendingPriceText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0277BD',
  },
  // Skeleton Loader Styles
  skeletonContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  skeletonHeader: {
    marginBottom: 24,
  },
  skeletonTitle: {
    width: 120,
    height: 24,
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
    marginBottom: 8,
  },
  skeletonSubtitle: {
    width: 80,
    height: 16,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
  },
  skeletonEventsContainer: {
    marginBottom: 24,
  },
  skeletonEventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  skeletonImage: {
    width: '100%',
    height: 120,
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
    marginBottom: 12,
  },
  skeletonContent: {
    gap: 8,
  },
  skeletonMeta: {
    width: 100,
    height: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  skeletonButton: {
    width: 80,
    height: 32,
    backgroundColor: '#E5E7EB',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  skeletonStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  skeletonStatCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  skeletonIcon: {
    width: 32,
    height: 32,
    backgroundColor: '#E5E7EB',
    borderRadius: 16,
    marginBottom: 8,
  },
  skeletonValue: {
    width: 40,
    height: 20,
    backgroundColor: '#E5E7EB',
    borderRadius: 8,
    marginBottom: 4,
  },
  skeletonLabel: {
    width: 60,
    height: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  // Empty State Styles
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 60,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  emptyStateIllustration: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  emptyStateTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 12,
    textAlign: 'center',
  },
  emptyStateDescription: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
    maxWidth: 280,
  },
  emptyStateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0277BD',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  emptyStateButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
});

export default homeStyles;
