import { StyleSheet } from 'react-native';

const organizerDashboardStyles = StyleSheet.create({
  modernDashboardContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingBottom: 60,
  },
  modernDashboardHeader: {
    backgroundColor: '#01579B',
    paddingTop: 40,
    paddingBottom: 20,
    paddingHorizontal: 18,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 10,
  },
  modernDashboardHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  modernDashboardProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modernDashboardAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modernDashboardAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 22,
  },
  modernDashboardWelcome: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.75)',
    marginBottom: 2,
  },
  modernDashboardName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  minimalStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 8,
    marginTop: 1,
  },
  minimalStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  minimalStatNumber: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    lineHeight: 15,
  },
  minimalStatLabel: {
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 11,
  },
  modernDashboardSettingsButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  modernDashboardStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    width: '90%',
    alignSelf: 'center',
  },
  modernDashboardStatCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 4,
    alignItems: 'flex-start',
    gap: 4,
  },
  modernDashboardStatIconContainer: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(2, 119, 189, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernDashboardStatIcon: {
    fontSize: 12,
    color: '#0277BD',
  },
  modernDashboardStatNumber: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
  },
  modernDashboardStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748B',
  },
  modernDashboardQuickActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    marginHorizontal: 20,
    gap: 10,
  },
  modernDashboardActionButton: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#0277BD',
  },
  modernDashboardActionGradient: {
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  modernDashboardActionText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  modernDashboardSecondaryButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#E0F2FE',
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modernDashboardSecondaryText: {
    color: '#0277BD',
    fontWeight: '700',
    fontSize: 12,
  },
  modernDashboardSection: {
    marginTop: 24,
    marginHorizontal: 20,
  },
  modernDashboardSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  modernDashboardSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
  },
  modernDashboardSectionCount: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0277BD',
  },
  modernDashboardEmptyState: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 26,
    paddingHorizontal: 18,
    alignItems: 'center',
    gap: 12,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
  },
  modernDashboardEmptyIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernDashboardEmptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
  },
  modernDashboardEmptyText: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 18,
  },
  modernDashboardEmptyButton: {
    width: '100%',
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 6,
  },
  modernDashboardEmptyButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
    backgroundColor: '#0277BD',
  },
  modernDashboardEmptyButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  dashboardSection: {
    marginTop: 20,
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    gap: 14,
  },
  modernDashboardGrowthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  modernDashboardGrowthText: {
    color: '#10B981',
    fontWeight: '700',
    fontSize: 11,
  },
  modernDashboardInsightsGrid: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  modernDashboardInsightCard: {
    flex: 1,
    backgroundColor: '#F8FBFF',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 14,
    gap: 8,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 4,
  },
  modernDashboardInsightIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(2, 119, 189, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernDashboardInsightValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 2,
  },
  modernDashboardInsightLabel: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '500',
  },
  advancedInsightsMainRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  advancedInsightsSecondaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 12,
  },
  advancedInsightCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  advancedInsightIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  advancedInsightValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 4,
  },
  advancedInsightLabel: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '500',
    marginBottom: 8,
  },
  advancedInsightTrend: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  advancedInsightTrendText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#10B981',
  },
  advancedInsightMiniChart: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  advancedInsightMiniChartText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  advancedInsightBadge: {
    backgroundColor: '#8B5CF6',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  advancedInsightBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  advancedInsightActivity: {
    backgroundColor: '#10B981',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  advancedInsightActivityText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  bestPerformingEventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  bestPerformingEventHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  bestPerformingEventIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  bestPerformingEventTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  bestPerformingEventContent: {
    marginBottom: 12,
  },
  bestPerformingEventName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 8,
  },
  bestPerformingEventStats: {
    flexDirection: 'row',
    gap: 16,
  },
  bestPerformingEventStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  bestPerformingEventStatText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  bestPerformingEventButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 16,
    right: 16,
  },
  performanceOverviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  performanceOverviewTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 16,
  },
  performanceMetrics: {
    gap: 16,
  },
  performanceMetric: {
    gap: 8,
  },
  performanceMetricValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1F2937',
  },
  performanceMetricLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  performanceMetricBar: {
    height: 6,
    backgroundColor: '#F3F4F6',
    borderRadius: 3,
    overflow: 'hidden',
  },
  performanceMetricBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  dashboardSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
  },
  dashboardSettings: {
    gap: 18,
  },
  settingsGroup: {
    gap: 10,
  },
  settingsGroupTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  dashboardSettingItem: {
    backgroundColor: '#F8FBFF',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  settingItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E0F2FE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardSettingIcon: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  dashboardSettingText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
  },
  dashboardSettingSubtext: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 1,
  },
  dashboardSettingArrow: {
    fontSize: 14,
    color: '#94A3B8',
  },
  dashboardEventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
    gap: 12,
  },
  dashboardEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  dashboardEventInfo: {
    flexDirection: 'row',
    gap: 12,
    flex: 1,
  },
  dashboardEventIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E0F2FE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardEventIcon: {
    fontSize: 18,
    color: '#0277BD',
  },
  dashboardEventDetails: {
    flex: 1,
    gap: 6,
  },
  dashboardEventTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
  },
  dashboardEventDate: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0277BD',
  },
  dashboardEventMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  dashboardEventStatusWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dashboardEventStatus: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  dashboardEventStatusText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#1E293B',
  },
  dashboardEventMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dashboardEventMetaValue: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748B',
  },
  dashboardEventFavoritesValue: {
    color: '#EF4444',
  },
  dashboardEventActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dashboardActionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
  },
  editButton: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  deleteButton: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  createEventOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  createEventModal: {
    width: '100%',
    maxHeight: '86%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 12,
  },
  createEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#F8FBFF',
  },
  createEventTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1E293B',
  },
  createEventClose: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  createEventCloseText: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '700',
  },
  createEventForm: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  createEventInputGroup: {
    marginTop: 14,
  },
  createEventLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 6,
  },
  createEventInput: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 13,
    color: '#1E293B',
    backgroundColor: '#F8FAFC',
  },
  createEventTextArea: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    fontSize: 13,
    color: '#1E293B',
    backgroundColor: '#F8FAFC',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  createEventRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  createEventActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 20,
  },
  createEventDraftButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#CBD5F5',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
  },
  createEventDraftText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
  },
  createEventPublishButton: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#0277BD',
    paddingVertical: 12,
    alignItems: 'center',
  },
  createEventPublishText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
});

export default organizerDashboardStyles;
